### ISSUE TITLE
'Required' fields on Personal Information form are not validated

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/MVP-Site#104] opened 2021-11-09 22:24 UTC
## Description
Currently, when submitting the Personal Information form, you are allowed to advance even if you do not provide a value for Official First Name, Official Last Name, Preferred Name, Company Name and Mentor, even though the labels for these have an asterisk indicating they are required fields.

## Expected behavior
Any field that displays with an asterisk in the field label should have an associated validator that stops the form submission and informs you that the field is required. This should also block it if a 'whitespace-only' value (like a space) is provided.

## Steps To Reproduce
1. Go to /Application
2. Advance your form to the Personal stage
3. Ensure that Preferred Name, Company Name, and Mentor have no values.
4. Press the "Next" button.
5. The form will advance to the Objectives stage

**NOTE:** I later tested removing values for official first name, and the same thing happened. Seems to be a form-wide issue of no validation.

## Possible Fix
Field validation should be added to ensure empty values are checked for on mandatory fields.

## Screenshots
![image](https://user-images.githubusercontent.com/4146192/141015156-9cd2384e-55e9-4ca3-be82-84dc743a41fb.png)

**Comment by robearlam** [comment] 2021-11-09 22:50
Closed as a dupe of #97 (Currently being deployed)

**Closed by robearlam** 2021-11-09 22:50 UTC
