### ISSUE TITLE
Invoke-RestMethod : Unable to connect to the remote server

### ISSUE THREAD

**Issue by stesels** [Sitecore/MVP-Site#30] opened 2021-09-15 10:54 UTC
## Description

ERROR: for solr-init  Container "7d4209d666c7" is unhealthy.
ERROR: Encountered errors while bringing up the project.
Waiting for CM to become available...
Invoke-RestMethod : Unable to connect to the remote server
At C:\GIT\3c_vso\twobirds\mainsite_rebuild\docker\up.ps1:50 char:19
+ ...   $status = Invoke-RestMethod "http://localhost:8079/api/http/routers ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

## Expected behavior

I was not able to complete my installation.

## Your Environment

* Browser Name and version:
* Operating System and version (desktop or mobile):
* Docker Version:

## Screenshots

![image](https://user-images.githubusercontent.com/82285391/133421031-61cbc647-a126-48d0-8f2b-c86fa0f0c60b.png)

**Comment by robearlam** [comment] 2021-09-16 01:24
Hi @stesels,

Can you please provide steps to reproduce this error so we can investigate? What you've provided so far isn't enough information for us to replicate this.

Thanks,
Rob

**Comment by stesels** [comment] 2021-09-20 13:08
Step 1: Ran a .\init.ps1
Step 2: Ran  .\docker\up.ps1

Following are the up.ps1
$ErrorActionPreference = "Stop";

# Double check whether init has been run
$envCheckVariable = "HOST_LICENSE_FOLDER"
$envCheck = Get-Content .env -Encoding UTF8 | Where-Object { $_ -imatch "^$envCheckVariable=.+" }
if (-not $envCheck.Substring($envCheckVariable.length + 1)) {
    throw "$envCheckVariable does not have a value. Did you run 'init.ps1 -InitEnv'?"
}

# If a local IIS is listening on port 443, it'll need to be stopped for now
if (Get-Command "iisreset" -errorAction SilentlyContinue)
{
    iisreset /stop
}

# Restore dotnet tool for sitecore login and serialization
dotnet tool restore

# Build all module containers
Write-Host "Building module containers i.e. Coveo..." -ForegroundColor Green
$coveoCheckVariable = "COVEO_RESOURCES_IMAGE"
$coveoCheck = (Get-Content .env -Encoding UTF8 | Where-Object { $_ -imatch "^$coveoCheckVariable=.+" }).Substring($coveoCheckVariable.length + 1)
if (-not $coveoCheck) {
    throw "$coveoCheckVariable does not have a value."
}
docker build --tag $coveoCheck .\docker\build\_modules\coveo --no-cache
if ($LASTEXITCODE -ne 0)
{
    Write-Error "Module container (i.e. Coveo) build failed, see errors above."
}

# Build all containers in the Sitecore instance, forcing a pull of latest base containers
Write-Host "Building containers..." -ForegroundColor Green
docker-compose build --no-cache
if ($LASTEXITCODE -ne 0)
{
    Write-Error "Container build failed, see errors above."
}

# Start the Sitecore instance
Write-Host "Starting Sitecore environment..." -ForegroundColor Green
docker-compose up -d

# Wait for Traefik to expose CM route
Write-Host "Waiting for CM to become available..." -ForegroundColor Green
$startTime = Get-Date
do {
    Start-Sleep -Milliseconds 100
    try {
        $status = Invoke-RestMethod "http://localhost:8079/api/http/routers/cm-secure@docker"
    } catch {
        if ($_.Exception.Response.StatusCode.value__ -ne "404") {
            throw
        }
    }
} while ($status.status -ne "enabled" -and $startTime.AddSeconds(15) -gt (Get-Date))
if (-not $status.status -eq "enabled") {
    $status
    Write-Error "Timeout waiting for Sitecore CM to become available via Traefik proxy. Check CM container logs."
}

dotnet sitecore login --cm https://twobirds-cm.sc.localhost/ --auth https://twobirds-id.sc.localhost/ --allow-write true
if ($LASTEXITCODE -ne 0) {
    Write-Error "Unable to log into Sitecore, did the Sitecore environment start correctly? See logs above."
}

# Populate Solr managed schemas to avoid errors during item push
Write-Host "Populating Solr managed schema..." -ForegroundColor Green
$token = (Get-Content .\.sitecore\user.json | ConvertFrom-Json).endpoints.default.accessToken
Invoke-RestMethod "https://twobirds-cm.sc.localhost/sitecore/admin/PopulateManagedSchema.aspx?indexes=all" -Headers @{Authorization = "Bearer $token"} -UseBasicParsing | Out-Null

Write-Host "Pushing latest items to Sitecore..." -ForegroundColor Green

#dotnet sitecore ser push --publish
dotnet sitecore ser push
if ($LASTEXITCODE -ne 0) {
    Write-Error "Serialization push failed, see errors above."
}
Write-Host "Don't forget to publish everything!!" -ForegroundColor Green
Write-Host "You can use the Sitecore CLI but it might be faster to do this in Sitecore direct" -ForegroundColor Green

Write-Host "Opening site..." -ForegroundColor Green

Start-Process https://twobirds-cm.sc.localhost/sitecore/
Start-Process https://twobirds.sc.localhost/

Write-Host ""
Write-Host "Use the following command to monitor your Rendering Host:" -ForegroundColor Green
Write-Host "docker-compose logs -f twobirds-rendering"
Write-Host ""

**Comment by robearlam** [comment] 2021-10-06 04:53
I tried to run this locally and it ran fine for me @stesels.

Looking at your screenshot above, its not from this solution, it looks like you're running a different solution based of XP.

I'm going close this as the issue isn't related to this MVP repository. To get help on running your custom solution in Docker you can ask questions in [Sitecore Stack Exchange](https://sitecore.stackexchange.com/) or the [Community Slack group](https://sitecore.chat/).

**Closed by robearlam** 2021-10-06 04:53 UTC
